import type { SignalInput } from '@/services/ingestion/schema'
import { LOCATION_IDS } from '@/data/seed/pilot'

/**
 * Development signal simulator.
 *
 * Generates realistic scenarios against the seeded Costco locations so the
 * entire Detect -> Locate -> Classify -> Validate -> Alert -> Acknowledge ->
 * Escalate -> Resolve -> Report workflow can be demonstrated without any live
 * integration.
 *
 * Every signal it produces is marked `collectionMethod: 'simulator'` and its
 * provenance says so plainly, so simulated content is never mistaken for
 * collected content.
 *
 * The text below is invented for demonstration. Handles are fictional
 * (`@demo_*`) and no real account, person or URL is referenced.
 */

export interface SimulationScenario {
  id: string
  title: string
  description: string
  /** What the analyst should observe when this scenario runs. */
  expectedOutcome: string
  locationId: string
  /** Signals are emitted in order; several means the scenario tests dedup. */
  build(now: Date): SignalInput[]
}

const minutesAgo = (now: Date, minutes: number): string =>
  new Date(now.getTime() - minutes * 60_000).toISOString()

const daysAgo = (now: Date, days: number): string =>
  new Date(now.getTime() - days * 86_400_000).toISOString()

/** Every simulated signal carries the same honest provenance statement. */
const PROVENANCE =
  'Generated by the OpeniWatch development simulator. This is not collected content.'

function simulated(
  partial: Omit<SignalInput, 'collectionMethod' | 'provenance' | 'sourcePlatform'> &
    Partial<Pick<SignalInput, 'sourcePlatform'>>,
): SignalInput {
  return {
    sourcePlatform: partial.sourcePlatform ?? 'Public web source',
    collectionMethod: 'simulator',
    provenance: PROVENANCE,
    ...partial,
  }
}

export const SIMULATION_SCENARIOS: readonly SimulationScenario[] = [
  {
    id: 'stafford-firearm',
    title: '1. Critical firearm report — Stafford parking lot',
    description:
      'A public post reports an individual displaying a firearm in the parking area of Costco #1487 in Stafford, TX.',
    expectedOutcome:
      'Classified as Weapon or firearm, matched to Costco #1487 with high confidence, scored critical, and queued for analyst review.',
    locationId: LOCATION_IDS.stafford,
    build: (now) => [
      simulated({
        sourceRecordId: `sim-stafford-firearm-${now.getTime()}`,
        sourceUrl: 'https://example.com/demo/stafford-firearm',
        originalText:
          'There is a guy in the parking lot at Costco #1487 in Stafford waving a gun around near the fuel station. He is wearing a grey hoodie and standing next to a white pickup. People are running back inside. Calling 911 right now.',
        publishedAt: minutesAgo(now, 2),
        author: {
          handle: '@demo_stafford_shopper',
          displayName: 'Demo Shopper',
          profileLocationText: 'Houston, TX',
          sourceProfileMetadata: { note: 'Simulated public profile attributes.' },
        },
        media: [],
        hasPublicGeotag: false,
        rawPayload: { simulator: true, scenario: 'stafford-firearm' },
      }),
    ],
  },

  {
    id: 'plano-confrontation',
    title: '2. High-severity confrontation — inside the Plano warehouse',
    description:
      'A physical altercation reported inside Costco #696 in Plano, TX, near the registers.',
    expectedOutcome:
      'Classified as Assault or confrontation, matched to Costco #696, scored high. Note that #696 carries two operational assignments.',
    locationId: LOCATION_IDS.plano,
    build: (now) => [
      simulated({
        sourceRecordId: `sim-plano-fight-${now.getTime()}`,
        sourceUrl: 'https://example.com/demo/plano-confrontation',
        originalText:
          'Big fight just broke out inside the warehouse at Costco #696 in Plano by the registers. Two guys throwing punches, staff trying to separate them. Happening now near the front entrance.',
        publishedAt: minutesAgo(now, 6),
        author: {
          handle: '@demo_plano_member',
          displayName: 'Demo Member',
          profileLocationText: 'Plano, TX',
          sourceProfileMetadata: { note: 'Simulated public profile attributes.' },
        },
        media: [],
        rawPayload: { simulator: true, scenario: 'plano-confrontation' },
      }),
    ],
  },

  {
    id: 'new-orleans-protest',
    title: '3. Moderate protest planning — near New Orleans',
    description:
      'A post organising a demonstration outside Costco #01147 on Dublin St., New Orleans, LA.',
    expectedOutcome:
      'Classified as Protest or organized disruption, matched to Costco #01147, scored moderate. Planned rather than in progress, so immediacy is lower.',
    locationId: LOCATION_IDS.newOrleans,
    build: (now) => [
      simulated({
        sourceRecordId: `sim-nola-protest-${now.getTime()}`,
        sourceUrl: 'https://example.com/demo/nola-protest',
        originalText:
          'We are organising a demonstration outside the Costco #01147 on Dublin St in New Orleans this Saturday at 10am. Bring signs. Peaceful protest, we will be on the sidewalk by the entrance.',
        publishedAt: minutesAgo(now, 180),
        author: {
          handle: '@demo_nola_organiser',
          displayName: 'Demo Community Group',
          profileLocationText: 'New Orleans, LA',
          sourceProfileMetadata: { note: 'Simulated public profile attributes.' },
        },
        media: [],
        rawPayload: { simulator: true, scenario: 'new-orleans-protest' },
      }),
    ],
  },

  {
    id: 'plano-complaint',
    title: '4. Informational customer complaint — should not raise an urgent alert',
    description:
      'A negative customer-experience post about the Plano warehouse: queues, staffing and pricing.',
    expectedOutcome:
      'Classified as General customer-experience disruption and held at informational. This is the check that complaint volume never competes with security matters for SOC attention.',
    locationId: LOCATION_IDS.plano,
    build: (now) => [
      simulated({
        sourceRecordId: `sim-plano-complaint-${now.getTime()}`,
        sourceUrl: 'https://example.com/demo/plano-complaint',
        originalText:
          'Waited 45 minutes in line at the Plano Costco today. Only two registers open, self-checkout was closed, and the rotisserie chicken was sold out again. Prices keep going up. Worst experience, never shopping here again.',
        publishedAt: minutesAgo(now, 25),
        author: {
          handle: '@demo_unhappy_member',
          displayName: 'Demo Member',
          profileLocationText: 'Frisco, TX',
          sourceProfileMetadata: { note: 'Simulated public profile attributes.' },
        },
        media: [],
        rawPayload: { simulator: true, scenario: 'plano-complaint' },
      }),
    ],
  },

  {
    id: 'memphis-old-repost',
    title: '5. Old reposted video — should be marked outdated',
    description:
      'A resurfaced clip of an incident at Costco #353 in Memphis, posted today but describing a past event.',
    expectedOutcome:
      'Severity capped at moderate because the text identifies itself as a repost. The analyst dispositions it as Outdated.',
    locationId: LOCATION_IDS.memphis,
    build: (now) => [
      simulated({
        sourceRecordId: `sim-memphis-repost-${now.getTime()}`,
        sourceUrl: 'https://example.com/demo/memphis-repost',
        originalText:
          'Reposting this old video of the fight that broke out at Costco #353 on Hacks Cross in Memphis. This is from last year but people should still see it. Wild scenes.',
        publishedAt: minutesAgo(now, 15),
        author: {
          handle: '@demo_repost_account',
          displayName: 'Demo Clips Account',
          profileLocationText: 'Memphis, TN',
          sourceProfileMetadata: { note: 'Simulated public profile attributes.' },
        },
        media: [
          {
            mediaType: 'video',
            url: 'https://example.com/demo/media/memphis-clip.mp4',
            caption: 'Simulated media reference. No real media is fetched.',
            capturedAt: daysAgo(now, 400),
          },
        ],
        rawPayload: { simulator: true, scenario: 'memphis-old-repost' },
      }),
    ],
  },

  {
    id: 'stafford-duplicates',
    title: '6. Duplicate reports from several accounts',
    description:
      'Four accounts report the same Stafford incident: one exact repost and three rewordings.',
    expectedOutcome:
      'The exact repost is marked duplicate automatically. The rewordings are surfaced as likely duplicates and counted as independent corroboration, which raises the priority score.',
    locationId: LOCATION_IDS.stafford,
    build: (now) => {
      const shared =
        'Man with a gun in the parking lot at Costco #1487 in Stafford, everyone is being told to stay inside.'
      return [
        simulated({
          sourceRecordId: `sim-dupe-a-${now.getTime()}`,
          sourceUrl: 'https://example.com/demo/dupe-a',
          originalText: shared,
          publishedAt: minutesAgo(now, 9),
          author: {
            handle: '@demo_account_one',
            displayName: 'Demo Account One',
            profileLocationText: 'Stafford, TX',
            sourceProfileMetadata: {},
          },
          rawPayload: { simulator: true, scenario: 'stafford-duplicates', variant: 'original' },
        }),
        simulated({
          sourceRecordId: `sim-dupe-b-${now.getTime()}`,
          sourceUrl: 'https://example.com/demo/dupe-b',
          // Byte-identical text from a different account: an exact repost.
          originalText: shared,
          publishedAt: minutesAgo(now, 8),
          author: {
            handle: '@demo_account_two',
            displayName: 'Demo Account Two',
            profileLocationText: 'Sugar Land, TX',
            sourceProfileMetadata: {},
          },
          rawPayload: { simulator: true, scenario: 'stafford-duplicates', variant: 'exact-repost' },
        }),
        simulated({
          sourceRecordId: `sim-dupe-c-${now.getTime()}`,
          sourceUrl: 'https://example.com/demo/dupe-c',
          originalText:
            'Man with a gun in the parking lot at Costco #1487 in Stafford, everyone is being told to stay inside the building right now.',
          publishedAt: minutesAgo(now, 7),
          author: {
            handle: '@demo_account_three',
            displayName: 'Demo Account Three',
            profileLocationText: 'Missouri City, TX',
            sourceProfileMetadata: {},
          },
          rawPayload: { simulator: true, scenario: 'stafford-duplicates', variant: 'reworded' },
        }),
        simulated({
          sourceRecordId: `sim-dupe-d-${now.getTime()}`,
          sourceUrl: 'https://example.com/demo/dupe-d',
          originalText:
            'Man with a gun in the parking lot at the Costco #1487 in Stafford, everyone is being told to stay inside, police are on the way.',
          publishedAt: minutesAgo(now, 6),
          author: {
            handle: '@demo_account_four',
            displayName: 'Demo Account Four',
            profileLocationText: 'Houston, TX',
            sourceProfileMetadata: {},
          },
          rawPayload: { simulator: true, scenario: 'stafford-duplicates', variant: 'reworded' },
        }),
      ]
    },
  },

  {
    id: 'mansfield-police',
    title: '7. Nearby police activity — Mansfield access',
    description:
      'Law-enforcement activity on US-287 near Costco #1381 in Mansfield, TX, affecting access.',
    expectedOutcome:
      'Classified as Nearby police activity. Operational relevance is reduced because the text places the event near, not on, the property.',
    locationId: LOCATION_IDS.mansfield,
    build: (now) => [
      simulated({
        sourceRecordId: `sim-mansfield-police-${now.getTime()}`,
        sourceUrl: 'https://example.com/demo/mansfield-police',
        originalText:
          'Heavy police activity on US-287 two blocks away from the Costco #1381 in Mansfield. Units everywhere, road is blocked and traffic is backed up. Cannot get into the lot from the highway side.',
        publishedAt: minutesAgo(now, 12),
        author: {
          handle: '@demo_mansfield_driver',
          displayName: 'Demo Commuter',
          profileLocationText: 'Mansfield, TX',
          sourceProfileMetadata: {},
        },
        rawPayload: { simulator: true, scenario: 'mansfield-police' },
      }),
    ],
  },

  {
    id: 'allentown-suspicious',
    title: '8. Unconfirmed suspicious activity — Allentown',
    description:
      'A hedged, second-hand report of suspicious behaviour near Costco #1211 in Allentown, PA.',
    expectedOutcome:
      'Classified as Suspicious activity with reduced source credibility because the report is second-hand and hedged. Author current location remains unknown.',
    locationId: LOCATION_IDS.allentown,
    build: (now) => [
      simulated({
        sourceRecordId: `sim-allentown-suspicious-${now.getTime()}`,
        sourceUrl: 'https://example.com/demo/allentown-suspicious',
        originalText:
          'I heard someone said there was allegedly a guy loitering around the Costco on N. Krocks Rd in Allentown looking into car windows. Supposedly he has been there a while. Not sure if it is true.',
        publishedAt: minutesAgo(now, 95),
        author: {
          handle: '@demo_allentown_local',
          displayName: 'Demo Local',
          profileLocationText: 'Allentown, PA',
          sourceProfileMetadata: {},
        },
        rawPayload: { simulator: true, scenario: 'allentown-suspicious' },
      }),
    ],
  },
]

export function getScenario(id: string): SimulationScenario | undefined {
  return SIMULATION_SCENARIOS.find((s) => s.id === id)
}
